// Mocks generated by Mockito 5.4.5 from annotations
// in captainvfr/test/widgets/flight_tracking_panel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:ui' as _i13;

import 'package:captainvfr/models/aircraft.dart' as _i12;
import 'package:captainvfr/models/airport.dart' as _i25;
import 'package:captainvfr/models/flight.dart' as _i8;
import 'package:captainvfr/models/flight_plan.dart' as _i21;
import 'package:captainvfr/models/flight_point.dart' as _i7;
import 'package:captainvfr/models/flight_segment.dart' as _i9;
import 'package:captainvfr/models/manufacturer.dart' as _i15;
import 'package:captainvfr/models/model.dart' as _i16;
import 'package:captainvfr/models/navaid.dart' as _i26;
import 'package:captainvfr/models/reporting_point.dart' as _i27;
import 'package:captainvfr/models/trip.dart' as _i5;
import 'package:captainvfr/services/aircraft_service.dart' as _i4;
import 'package:captainvfr/services/aircraft_settings_service.dart' as _i14;
import 'package:captainvfr/services/barometer_service.dart' as _i17;
import 'package:captainvfr/services/flight_plan_service.dart' as _i20;
import 'package:captainvfr/services/flight_plan_tile_download_service.dart'
    as _i22;
import 'package:captainvfr/services/flight_service.dart' as _i6;
import 'package:captainvfr/services/heading_service.dart' as _i18;
import 'package:captainvfr/services/manufacturer_service.dart' as _i2;
import 'package:captainvfr/services/model_service.dart' as _i3;
import 'package:captainvfr/services/settings_service.dart' as _i19;
import 'package:captainvfr/services/spatial_airspace_service.dart' as _i28;
import 'package:flutter/material.dart' as _i23;
import 'package:latlong2/latlong.dart' as _i24;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDuration_0 extends _i1.SmartFake implements Duration {
  _FakeDuration_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeManufacturerService_1 extends _i1.SmartFake
    implements _i2.ManufacturerService {
  _FakeManufacturerService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeModelService_2 extends _i1.SmartFake implements _i3.ModelService {
  _FakeModelService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAircraftService_3 extends _i1.SmartFake
    implements _i4.AircraftService {
  _FakeAircraftService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTrip_4 extends _i1.SmartFake implements _i5.Trip {
  _FakeTrip_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FlightService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlightService extends _i1.Mock implements _i6.FlightService {
  MockFlightService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i7.FlightPoint> get flightPath => (super.noSuchMethod(
        Invocation.getter(#flightPath),
        returnValue: <_i7.FlightPoint>[],
      ) as List<_i7.FlightPoint>);

  @override
  List<_i8.Flight> get flights => (super.noSuchMethod(
        Invocation.getter(#flights),
        returnValue: <_i8.Flight>[],
      ) as List<_i8.Flight>);

  @override
  bool get isTracking => (super.noSuchMethod(
        Invocation.getter(#isTracking),
        returnValue: false,
      ) as bool);

  @override
  double get fuelUsed => (super.noSuchMethod(
        Invocation.getter(#fuelUsed),
        returnValue: 0.0,
      ) as double);

  @override
  List<_i9.FlightSegment> get flightSegments => (super.noSuchMethod(
        Invocation.getter(#flightSegments),
        returnValue: <_i9.FlightSegment>[],
      ) as List<_i9.FlightSegment>);

  @override
  String get formattedFlightTime => (super.noSuchMethod(
        Invocation.getter(#formattedFlightTime),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#formattedFlightTime),
        ),
      ) as String);

  @override
  Duration get flightDuration => (super.noSuchMethod(
        Invocation.getter(#flightDuration),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#flightDuration),
        ),
      ) as Duration);

  @override
  Duration get movingTime => (super.noSuchMethod(
        Invocation.getter(#movingTime),
        returnValue: _FakeDuration_0(
          this,
          Invocation.getter(#movingTime),
        ),
      ) as Duration);

  @override
  String get formattedMovingTime => (super.noSuchMethod(
        Invocation.getter(#formattedMovingTime),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#formattedMovingTime),
        ),
      ) as String);

  @override
  double get totalDistance => (super.noSuchMethod(
        Invocation.getter(#totalDistance),
        returnValue: 0.0,
      ) as double);

  @override
  double get maxSpeed => (super.noSuchMethod(
        Invocation.getter(#maxSpeed),
        returnValue: 0.0,
      ) as double);

  @override
  double get currentSpeed => (super.noSuchMethod(
        Invocation.getter(#currentSpeed),
        returnValue: 0.0,
      ) as double);

  @override
  double get averageSpeed => (super.noSuchMethod(
        Invocation.getter(#averageSpeed),
        returnValue: 0.0,
      ) as double);

  @override
  double get verticalSpeed => (super.noSuchMethod(
        Invocation.getter(#verticalSpeed),
        returnValue: 0.0,
      ) as double);

  @override
  double get currentGForce => (super.noSuchMethod(
        Invocation.getter(#currentGForce),
        returnValue: 0.0,
      ) as double);

  @override
  double get currentPressure => (super.noSuchMethod(
        Invocation.getter(#currentPressure),
        returnValue: 0.0,
      ) as double);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i11.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void setAircraft(_i12.Aircraft? aircraft) => super.noSuchMethod(
        Invocation.method(
          #setAircraft,
          [aircraft],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> startTracking() => (super.noSuchMethod(
        Invocation.method(
          #startTracking,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<_i8.Flight?> stopTracking() => (super.noSuchMethod(
        Invocation.method(
          #stopTracking,
          [],
        ),
        returnValue: _i11.Future<_i8.Flight?>.value(),
      ) as _i11.Future<_i8.Flight?>);

  @override
  _i11.Future<void> deleteFlight(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteFlight,
          [index],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<String> exportFlight(
    _i8.Flight? flight, {
    String? format = 'gpx',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportFlight,
          [flight],
          {#format: format},
        ),
        returnValue: _i11.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #exportFlight,
            [flight],
            {#format: format},
          ),
        )),
      ) as _i11.Future<String>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AircraftSettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAircraftSettingsService extends _i1.Mock
    implements _i14.AircraftSettingsService {
  MockAircraftSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ManufacturerService get manufacturerService => (super.noSuchMethod(
        Invocation.getter(#manufacturerService),
        returnValue: _FakeManufacturerService_1(
          this,
          Invocation.getter(#manufacturerService),
        ),
      ) as _i2.ManufacturerService);

  @override
  _i3.ModelService get modelService => (super.noSuchMethod(
        Invocation.getter(#modelService),
        returnValue: _FakeModelService_2(
          this,
          Invocation.getter(#modelService),
        ),
      ) as _i3.ModelService);

  @override
  _i4.AircraftService get aircraftService => (super.noSuchMethod(
        Invocation.getter(#aircraftService),
        returnValue: _FakeAircraftService_3(
          this,
          Invocation.getter(#aircraftService),
        ),
      ) as _i4.AircraftService);

  @override
  List<_i15.Manufacturer> get manufacturers => (super.noSuchMethod(
        Invocation.getter(#manufacturers),
        returnValue: <_i15.Manufacturer>[],
      ) as List<_i15.Manufacturer>);

  @override
  List<_i16.Model> get models => (super.noSuchMethod(
        Invocation.getter(#models),
        returnValue: <_i16.Model>[],
      ) as List<_i16.Model>);

  @override
  List<_i12.Aircraft> get aircrafts => (super.noSuchMethod(
        Invocation.getter(#aircrafts),
        returnValue: <_i12.Aircraft>[],
      ) as List<_i12.Aircraft>);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i11.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> addManufacturer(
    String? name, {
    String? website,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addManufacturer,
          [name],
          {#website: website},
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> updateManufacturer(_i15.Manufacturer? manufacturer) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateManufacturer,
          [manufacturer],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> deleteManufacturer(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteManufacturer,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> addModel(
    String? name,
    String? manufacturerId,
    _i16.AircraftCategory? category, {
    int? engineCount = 1,
    int? maxSeats = 2,
    int? typicalCruiseSpeed = 100,
    int? typicalServiceCeiling = 10000,
    String? description,
    double? fuelConsumption,
    int? maximumClimbRate,
    int? maximumDescentRate,
    int? maxTakeoffWeight,
    int? maxLandingWeight,
    int? fuelCapacity,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addModel,
          [
            name,
            manufacturerId,
            category,
          ],
          {
            #engineCount: engineCount,
            #maxSeats: maxSeats,
            #typicalCruiseSpeed: typicalCruiseSpeed,
            #typicalServiceCeiling: typicalServiceCeiling,
            #description: description,
            #fuelConsumption: fuelConsumption,
            #maximumClimbRate: maximumClimbRate,
            #maximumDescentRate: maximumDescentRate,
            #maxTakeoffWeight: maxTakeoffWeight,
            #maxLandingWeight: maxLandingWeight,
            #fuelCapacity: fuelCapacity,
          },
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> updateModel(_i16.Model? model) => (super.noSuchMethod(
        Invocation.method(
          #updateModel,
          [model],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> deleteModel(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteModel,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> addAircraft(_i12.Aircraft? aircraft) => (super.noSuchMethod(
        Invocation.method(
          #addAircraft,
          [aircraft],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> updateAircraft(_i12.Aircraft? aircraft) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAircraft,
          [aircraft],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> deleteAircraft(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAircraft,
          [id],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  List<_i16.Model> getModelsForManufacturer(String? manufacturerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getModelsForManufacturer,
          [manufacturerId],
        ),
        returnValue: <_i16.Model>[],
      ) as List<_i16.Model>);

  @override
  List<_i12.Aircraft> getAircraftsForModel(String? modelId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAircraftsForModel,
          [modelId],
        ),
        returnValue: <_i12.Aircraft>[],
      ) as List<_i12.Aircraft>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [BarometerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBarometerService extends _i1.Mock implements _i17.BarometerService {
  MockBarometerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Stream<_i17.BarometerReading> get onBarometerUpdate =>
      (super.noSuchMethod(
        Invocation.getter(#onBarometerUpdate),
        returnValue: _i11.Stream<_i17.BarometerReading>.empty(),
      ) as _i11.Stream<_i17.BarometerReading>);

  @override
  double get seaLevelPressure => (super.noSuchMethod(
        Invocation.getter(#seaLevelPressure),
        returnValue: 0.0,
      ) as double);

  @override
  bool get isBarometerAvailable => (super.noSuchMethod(
        Invocation.getter(#isBarometerAvailable),
        returnValue: false,
      ) as bool);

  @override
  bool get isListening => (super.noSuchMethod(
        Invocation.getter(#isListening),
        returnValue: false,
      ) as bool);

  @override
  _i11.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> startListening() => (super.noSuchMethod(
        Invocation.method(
          #startListening,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void setSeaLevelPressure(double? pressureHPa) => super.noSuchMethod(
        Invocation.method(
          #setSeaLevelPressure,
          [pressureHPa],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> stopListening() => (super.noSuchMethod(
        Invocation.method(
          #stopListening,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HeadingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHeadingService extends _i1.Mock implements _i18.HeadingService {
  MockHeadingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get isRunning => (super.noSuchMethod(
        Invocation.getter(#isRunning),
        returnValue: false,
      ) as bool);

  @override
  bool get hasCompass => (super.noSuchMethod(
        Invocation.getter(#hasCompass),
        returnValue: false,
      ) as bool);

  @override
  bool get hasError => (super.noSuchMethod(
        Invocation.getter(#hasError),
        returnValue: false,
      ) as bool);

  @override
  bool get isCompassAvailable => (super.noSuchMethod(
        Invocation.getter(#isCompassAvailable),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i11.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> retryStart() => (super.noSuchMethod(
        Invocation.method(
          #retryStart,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> startHeadingUpdates() => (super.noSuchMethod(
        Invocation.method(
          #startHeadingUpdates,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void stopHeadingUpdates() => super.noSuchMethod(
        Invocation.method(
          #stopHeadingUpdates,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getFormattedHeading() => (super.noSuchMethod(
        Invocation.method(
          #getFormattedHeading,
          [],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #getFormattedHeading,
            [],
          ),
        ),
      ) as String);

  @override
  String getCardinalDirection() => (super.noSuchMethod(
        Invocation.method(
          #getCardinalDirection,
          [],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #getCardinalDirection,
            [],
          ),
        ),
      ) as String);

  @override
  _i11.Future<void> requestCalibration() => (super.noSuchMethod(
        Invocation.method(
          #requestCalibration,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i19.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get rotateMapWithHeading => (super.noSuchMethod(
        Invocation.getter(#rotateMapWithHeading),
        returnValue: false,
      ) as bool);

  @override
  _i19.MapRotationMode get mapRotationMode => (super.noSuchMethod(
        Invocation.getter(#mapRotationMode),
        returnValue: _i19.MapRotationMode.none,
      ) as _i19.MapRotationMode);

  @override
  bool get showAirspaces => (super.noSuchMethod(
        Invocation.getter(#showAirspaces),
        returnValue: false,
      ) as bool);

  @override
  bool get showNavaids => (super.noSuchMethod(
        Invocation.getter(#showNavaids),
        returnValue: false,
      ) as bool);

  @override
  bool get autoSaveFlights => (super.noSuchMethod(
        Invocation.getter(#autoSaveFlights),
        returnValue: false,
      ) as bool);

  @override
  bool get highPrecisionTracking => (super.noSuchMethod(
        Invocation.getter(#highPrecisionTracking),
        returnValue: false,
      ) as bool);

  @override
  bool get darkMode => (super.noSuchMethod(
        Invocation.getter(#darkMode),
        returnValue: false,
      ) as bool);

  @override
  String get units => (super.noSuchMethod(
        Invocation.getter(#units),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#units),
        ),
      ) as String);

  @override
  String get pressureUnit => (super.noSuchMethod(
        Invocation.getter(#pressureUnit),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#pressureUnit),
        ),
      ) as String);

  @override
  String get altitudeUnit => (super.noSuchMethod(
        Invocation.getter(#altitudeUnit),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#altitudeUnit),
        ),
      ) as String);

  @override
  String get distanceUnit => (super.noSuchMethod(
        Invocation.getter(#distanceUnit),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#distanceUnit),
        ),
      ) as String);

  @override
  String get speedUnit => (super.noSuchMethod(
        Invocation.getter(#speedUnit),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#speedUnit),
        ),
      ) as String);

  @override
  String get temperatureUnit => (super.noSuchMethod(
        Invocation.getter(#temperatureUnit),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#temperatureUnit),
        ),
      ) as String);

  @override
  String get weightUnit => (super.noSuchMethod(
        Invocation.getter(#weightUnit),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#weightUnit),
        ),
      ) as String);

  @override
  String get fuelUnit => (super.noSuchMethod(
        Invocation.getter(#fuelUnit),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#fuelUnit),
        ),
      ) as String);

  @override
  String get windUnit => (super.noSuchMethod(
        Invocation.getter(#windUnit),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.getter(#windUnit),
        ),
      ) as String);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  bool get autoCreateLogbookEntry => (super.noSuchMethod(
        Invocation.getter(#autoCreateLogbookEntry),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i11.Future<void> setRotateMapWithHeading(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setRotateMapWithHeading,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setMapRotationMode(_i19.MapRotationMode? mode) =>
      (super.noSuchMethod(
        Invocation.method(
          #setMapRotationMode,
          [mode],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setShowAirspaces(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setShowAirspaces,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setShowNavaids(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setShowNavaids,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setAutoSaveFlights(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setAutoSaveFlights,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setHighPrecisionTracking(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHighPrecisionTracking,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setDarkMode(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setDarkMode,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setUnits(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setUnits,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setPressureUnit(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setPressureUnit,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setAltitudeUnit(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setAltitudeUnit,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setDistanceUnit(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setDistanceUnit,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setSpeedUnit(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setSpeedUnit,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setTemperatureUnit(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setTemperatureUnit,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setWeightUnit(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setWeightUnit,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setFuelUnit(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setFuelUnit,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setWindUnit(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setWindUnit,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> setAutoCreateLogbookEntry(bool? value) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAutoCreateLogbookEntry,
          [value],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> resetToDefaults() => (super.noSuchMethod(
        Invocation.method(
          #resetToDefaults,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  double convertAltitude(double? meters) => (super.noSuchMethod(
        Invocation.method(
          #convertAltitude,
          [meters],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double convertDistance(double? meters) => (super.noSuchMethod(
        Invocation.method(
          #convertDistance,
          [meters],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double convertSpeed(double? metersPerSecond) => (super.noSuchMethod(
        Invocation.method(
          #convertSpeed,
          [metersPerSecond],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double convertWindSpeed(double? metersPerSecond) => (super.noSuchMethod(
        Invocation.method(
          #convertWindSpeed,
          [metersPerSecond],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double convertTemperature(double? celsius) => (super.noSuchMethod(
        Invocation.method(
          #convertTemperature,
          [celsius],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double convertWeight(double? kilograms) => (super.noSuchMethod(
        Invocation.method(
          #convertWeight,
          [kilograms],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double convertFuel(double? liters) => (super.noSuchMethod(
        Invocation.method(
          #convertFuel,
          [liters],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double convertAltitudeToMeters(double? value) => (super.noSuchMethod(
        Invocation.method(
          #convertAltitudeToMeters,
          [value],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double convertDistanceToMeters(double? value) => (super.noSuchMethod(
        Invocation.method(
          #convertDistanceToMeters,
          [value],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double convertSpeedToMPS(double? value) => (super.noSuchMethod(
        Invocation.method(
          #convertSpeedToMPS,
          [value],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double convertTemperatureToCelsius(double? value) => (super.noSuchMethod(
        Invocation.method(
          #convertTemperatureToCelsius,
          [value],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double convertWeightToKg(double? value) => (super.noSuchMethod(
        Invocation.method(
          #convertWeightToKg,
          [value],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double convertFuelToLiters(double? value) => (super.noSuchMethod(
        Invocation.method(
          #convertFuelToLiters,
          [value],
        ),
        returnValue: 0.0,
      ) as double);

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [FlightPlanService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlightPlanService extends _i1.Mock implements _i20.FlightPlanService {
  MockFlightPlanService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onFlightPlanLoaded(void Function(_i21.FlightPlan)? _onFlightPlanLoaded) =>
      super.noSuchMethod(
        Invocation.setter(
          #onFlightPlanLoaded,
          _onFlightPlanLoaded,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get isPlanning => (super.noSuchMethod(
        Invocation.getter(#isPlanning),
        returnValue: false,
      ) as bool);

  @override
  bool get isFlightPlanVisible => (super.noSuchMethod(
        Invocation.getter(#isFlightPlanVisible),
        returnValue: false,
      ) as bool);

  @override
  List<_i21.Waypoint> get waypoints => (super.noSuchMethod(
        Invocation.getter(#waypoints),
        returnValue: <_i21.Waypoint>[],
      ) as List<_i21.Waypoint>);

  @override
  List<_i21.FlightPlan> get savedFlightPlans => (super.noSuchMethod(
        Invocation.getter(#savedFlightPlans),
        returnValue: <_i21.FlightPlan>[],
      ) as List<_i21.FlightPlan>);

  @override
  List<_i5.Trip> get savedTrips => (super.noSuchMethod(
        Invocation.getter(#savedTrips),
        returnValue: <_i5.Trip>[],
      ) as List<_i5.Trip>);

  @override
  List<_i21.FlightPlan> get currentTripPlans => (super.noSuchMethod(
        Invocation.getter(#currentTripPlans),
        returnValue: <_i21.FlightPlan>[],
      ) as List<_i21.FlightPlan>);

  @override
  bool get isAnalyzingProfile => (super.noSuchMethod(
        Invocation.getter(#isAnalyzingProfile),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void setTileDownloadService(_i22.FlightPlanTileDownloadService? service) =>
      super.noSuchMethod(
        Invocation.method(
          #setTileDownloadService,
          [service],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setContext(_i23.BuildContext? context) => super.noSuchMethod(
        Invocation.method(
          #setContext,
          [context],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> saveCurrentFlightPlan({String? customName}) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveCurrentFlightPlan,
          [],
          {#customName: customName},
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void loadFlightPlan(String? flightPlanId) => super.noSuchMethod(
        Invocation.method(
          #loadFlightPlan,
          [flightPlanId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> deleteFlightPlan(String? flightPlanId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFlightPlan,
          [flightPlanId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> duplicateFlightPlan(String? flightPlanId) =>
      (super.noSuchMethod(
        Invocation.method(
          #duplicateFlightPlan,
          [flightPlanId],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<void> addFlightPlanToTrip(_i21.FlightPlan? newFlightPlan) =>
      (super.noSuchMethod(
        Invocation.method(
          #addFlightPlanToTrip,
          [newFlightPlan],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  _i11.Future<_i5.Trip> createTripFromFlightPlans(
    List<_i21.FlightPlan>? flightPlans,
    String? tripName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTripFromFlightPlans,
          [
            flightPlans,
            tripName,
          ],
        ),
        returnValue: _i11.Future<_i5.Trip>.value(_FakeTrip_4(
          this,
          Invocation.method(
            #createTripFromFlightPlans,
            [
              flightPlans,
              tripName,
            ],
          ),
        )),
      ) as _i11.Future<_i5.Trip>);

  @override
  _i11.Future<void> removeLegFromTrip(int? legIndex) => (super.noSuchMethod(
        Invocation.method(
          #removeLegFromTrip,
          [legIndex],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void loadTrip(String? tripId) => super.noSuchMethod(
        Invocation.method(
          #loadTrip,
          [tripId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void startNewFlightPlan({
    String? name,
    bool? enablePlanning = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #startNewFlightPlan,
          [],
          {
            #name: name,
            #enablePlanning: enablePlanning,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void createNewFlightPlan({bool? enablePlanning = false}) =>
      super.noSuchMethod(
        Invocation.method(
          #createNewFlightPlan,
          [],
          {#enablePlanning: enablePlanning},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addWaypoint(
    _i24.LatLng? position, {
    double? altitude,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addWaypoint,
          [position],
          {#altitude: altitude},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void insertWaypointAt(
    int? index,
    _i24.LatLng? position, {
    double? altitude,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #insertWaypointAt,
          [
            index,
            position,
          ],
          {#altitude: altitude},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addAirportWaypoint(
    _i25.Airport? airport, {
    double? altitude = 3000.0,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addAirportWaypoint,
          [airport],
          {#altitude: altitude},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addNavaidWaypoint(
    _i26.Navaid? navaid, {
    double? altitude = 3000.0,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addNavaidWaypoint,
          [navaid],
          {#altitude: altitude},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addReportingPointWaypoint(
    _i27.ReportingPoint? reportingPoint, {
    double? altitude = 3000.0,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #addReportingPointWaypoint,
          [reportingPoint],
          {#altitude: altitude},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeWaypoint(int? index) => super.noSuchMethod(
        Invocation.method(
          #removeWaypoint,
          [index],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeLastWaypoint() => super.noSuchMethod(
        Invocation.method(
          #removeLastWaypoint,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateWaypointAltitude(
    int? index,
    double? altitude,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateWaypointAltitude,
          [
            index,
            altitude,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateWaypointName(
    int? index,
    String? name,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateWaypointName,
          [
            index,
            name,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateWaypointNotes(
    int? index,
    String? notes,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateWaypointNotes,
          [
            index,
            notes,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateWaypointType(
    int? index,
    _i21.WaypointType? type,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateWaypointType,
          [
            index,
            type,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateWaypointPosition(
    int? index,
    _i24.LatLng? newPosition, {
    bool? isDragging = false,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #updateWaypointPosition,
          [
            index,
            newPosition,
          ],
          {#isDragging: isDragging},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateCruiseSpeed(double? speed) => super.noSuchMethod(
        Invocation.method(
          #updateCruiseSpeed,
          [speed],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateFuelConsumptionRate(double? rate) => super.noSuchMethod(
        Invocation.method(
          #updateFuelConsumptionRate,
          [rate],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateAircraft(String? aircraftId) => super.noSuchMethod(
        Invocation.method(
          #updateAircraft,
          [aircraftId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearFlightPlan() => super.noSuchMethod(
        Invocation.method(
          #clearFlightPlan,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void togglePlanningMode() => super.noSuchMethod(
        Invocation.method(
          #togglePlanningMode,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void toggleFlightPlanVisibility() => super.noSuchMethod(
        Invocation.method(
          #toggleFlightPlanVisibility,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFlightPlanVisibility(bool? visible) => super.noSuchMethod(
        Invocation.method(
          #setFlightPlanVisibility,
          [visible],
        ),
        returnValueForMissingStub: null,
      );

  @override
  String getFlightPlanSummary() => (super.noSuchMethod(
        Invocation.method(
          #getFlightPlanSummary,
          [],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #getFlightPlanSummary,
            [],
          ),
        ),
      ) as String);

  @override
  void reorderWaypoints(
    int? oldIndex,
    int? newIndex,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #reorderWaypoints,
          [
            oldIndex,
            newIndex,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  double calculateAltitudeChange({
    required double? startAltitude,
    required double? targetAltitude,
    required double? distanceNM,
    required double? cruiseSpeedKnots,
    double? maxClimbRate,
    double? maxDescentRate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateAltitudeChange,
          [],
          {
            #startAltitude: startAltitude,
            #targetAltitude: targetAltitude,
            #distanceNM: distanceNM,
            #cruiseSpeedKnots: cruiseSpeedKnots,
            #maxClimbRate: maxClimbRate,
            #maxDescentRate: maxDescentRate,
          },
        ),
        returnValue: 0.0,
      ) as double);

  @override
  double capAltitudeToServiceCeiling(
    double? requestedAltitude, {
    double? serviceCeiling,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #capAltitudeToServiceCeiling,
          [requestedAltitude],
          {#serviceCeiling: serviceCeiling},
        ),
        returnValue: 0.0,
      ) as double);

  @override
  void updateWaypointAltitudeWithValidation(
    int? index,
    double? requestedAltitude,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #updateWaypointAltitudeWithValidation,
          [
            index,
            requestedAltitude,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recalculateAllWaypointAltitudes() => super.noSuchMethod(
        Invocation.method(
          #recalculateAllWaypointAltitudes,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAircraftForFlightPlan(String? aircraftId) => super.noSuchMethod(
        Invocation.method(
          #setAircraftForFlightPlan,
          [aircraftId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setSpatialAirspaceService(_i28.SpatialAirspaceService? service) =>
      super.noSuchMethod(
        Invocation.method(
          #setSpatialAirspaceService,
          [service],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i11.Future<void> analyzeCurrentFlightPath() => (super.noSuchMethod(
        Invocation.method(
          #analyzeCurrentFlightPath,
          [],
        ),
        returnValue: _i11.Future<void>.value(),
        returnValueForMissingStub: _i11.Future<void>.value(),
      ) as _i11.Future<void>);

  @override
  void clearAirspaceProfile() => super.noSuchMethod(
        Invocation.method(
          #clearAirspaceProfile,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
