// Mocks generated by Mockito 5.4.5 from annotations
// in captainvfr/test/services/flight_service_altitude_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:captainvfr/services/barometer_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BarometerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBarometerService extends _i1.Mock implements _i2.BarometerService {
  MockBarometerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i2.BarometerReading> get onBarometerUpdate => (super.noSuchMethod(
        Invocation.getter(#onBarometerUpdate),
        returnValue: _i3.Stream<_i2.BarometerReading>.empty(),
      ) as _i3.Stream<_i2.BarometerReading>);

  @override
  double get seaLevelPressure => (super.noSuchMethod(
        Invocation.getter(#seaLevelPressure),
        returnValue: 0.0,
      ) as double);

  @override
  bool get isBarometerAvailable => (super.noSuchMethod(
        Invocation.getter(#isBarometerAvailable),
        returnValue: false,
      ) as bool);

  @override
  bool get isListening => (super.noSuchMethod(
        Invocation.getter(#isListening),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> startListening() => (super.noSuchMethod(
        Invocation.method(
          #startListening,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void setSeaLevelPressure(double? pressureHPa) => super.noSuchMethod(
        Invocation.method(
          #setSeaLevelPressure,
          [pressureHPa],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> stopListening() => (super.noSuchMethod(
        Invocation.method(
          #stopListening,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
